apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storarge: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.3.20  
    path: /var/nfs/jegan/share2  # Replace this path with your path /var/nfs/user15/share1
