apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
  - port: "3306" 
    protocolo: TCP
    targetPort: "3306" 
  selector:
    app: mariadb
  type: ClusterIP
status:
  loadBalancer: {}
