apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hello
  labels:
    app: hello
---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-build
  labels:
    app: hello
spec:
  triggers:
  - type: ImageChange
    imageChange: {}
  source:
    type: Git
    git:
      uri https://github.com/tektutor/spring-ms.git
    poll: true
  contextDir: /
strategy:
  type: Docker 
  sourceStrategy:
    from:
      kind: ImageStreamTag
      name: hello:latest
  output:
    to:
      kind ImageStreamTag
      name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: hello:1.0
        name: hello
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: hello
    weight: null
status: {}
